DROP TABLE IF EXISTS RUN;
DROP TABLE IF EXISTS STUDENT;

CREATE TABLE STUDENT(
  USER_ID text PRIMARY KEY,
  GENRE text NOT NULL DEFAULT '',
  MIX_ID text NOT NULL DEFAULT '',
  TOTAL_DISTANCE int NOT NULL DEFAULT 0,
  OVERALL_PACE real NOT NULL DEFAULT 0.5
);

CREATE TABLE RUN(
  USER_ID text REFERENCES STUDENT(USER_ID),
  SECONDS int NOT NULL DEFAULT 0,
  MINUTES int NOT NULL DEFAULT 0,
  HOURS int NOT NULL DEFAULT 0,
  DISTANCE float NOT NULL DEFAULT 0,
  TIMESTAMP text NOT NULL DEFAULT '',
  COORDINATES text NOT NULL DEFAULT '',
);
