DROP TABLE IF EXISTS RUN;
DROP TABLE IF EXISTS STUDENT;

CREATE TABLE STUDENT(
  USER_ID text PRIMARY KEY,
  GENRE text NOT NULL DEFAULT '',
  DISTANCE int NOT NULL DEFAULT 0
);

CREATE TABLE RUN(
  USER_ID text REFERENCES STUDENT(USER_ID),
  RUN_TYPE text NOT NULL DEFAULT '',
  SOURCE text NOT NULL DEFAULT '',
  DESTINATION text NOT NULL DEFAULT '',
  DISTANCE int NOT NULL DEFAULT 0,
  DATE_TIME timestamp DEFAULT CURRENT_TIMESTAMP
);
